# Generated by Django 6.0.5 on 2026-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('edat_minima', models.IntegerField()),
                ('edat_maxima', models.IntegerField()),
                ('distancia_km', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ['edat_minima'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognoms', models.CharField(max_length=100)),
                ('dorsal', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_naixement', models.DateField()),
                ('temps_segons', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cursa.categoria')),
            ],
            options={
                'ordering': ['dorsal'],
            },
        ),
    ]
